### ISSUE TITLE
Name inconsistency?

### ISSUE THREAD

**Issue by cm8263** [FAXES/SimpleBot#1]
`package.json`, lines 2 to 4:
```json
    "name": "multbbot",
    "version": "1.0.0",
    "description": "MultiBot developed by FAXES",
```
Bot seems to be called `SimpleBot` everywhere else (such as line 1 of `index.js`), was this intentional? Either way, thanks for giving back to the community, again ;)

**Comment by FAXES** [comment]
https://github.com/FAXES/SimpleBot/commit/0eb9f9ad3c06629c7191309fd3c57f4fc8999dbe
